# Generated by Django 4.2.7 on 2024-01-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_tblbadmin_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbluser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('on_delete', models.BooleanField(default=0)),
            ],
        ),
    ]
