# Generated by Django 4.2.7 on 2024-01-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_tbluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file')),
                ('filename', models.CharField(max_length=50)),
                ('create_on', models.DateField(auto_now_add=True)),
                ('modify_on', models.DateField()),
                ('expriey_on', models.DateField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_file_user', to='App.tbluser')),
            ],
        ),
    ]
