# Generated by Django 4.2.7 on 2024-02-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_tblfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblfile',
            name='request',
            field=models.BooleanField(default=0),
        ),
    ]
