# Generated by Django 4.2.7 on 2024-02-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_tblfile_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblfile',
            name='delete_on',
            field=models.BooleanField(default=0),
        ),
    ]
